#!/bin/bash

# Script om Oracle Java 8 te installeren. Je moet
# superuser zijn om dit te doen:
#
# Op Lubuntu:
#  
#  sudo install_java8
#
# Op Debian:
#  
#  su
#  ./install_java8
#

echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee /etc/apt/sources.list.d/webupd8team-java.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu xenial main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886
apt-get update
apt-get install oracle-java8-installer