#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

my_script_path=`realpath $0`
my_folder_path=`dirname $my_script_path`
build_folder=$my_folder_path/build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cd ..
cd Lessen
cd Voorwoord     ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_00.md; cd ..
cd 2_knop_if_else; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_01.md; cd ..
cd 4_FSR         ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_02.md; cd ..
cd 10_LDR        ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_03.md; cd ..

cd $build_folder

cat README_00.md >> README.md; echo " " >> README.md
cat README_01.md >> README.md; echo " " >> README.md
cat README_02.md >> README.md; echo " " >> README.md
cat README_03.md >> README.md; echo " " >> README.md

pandoc README.md -o boek.pdf --toc --toc-depth=1 --highlight-style=tango
cp boek.pdf ../../Boek/Boek_sensor_zonder_voorpagina.pdf

cd ../../Boek
pdfunite Boek_voorpagina.pdf Boek_sensor_zonder_voorpagina.pdf Boek_sensor.pdf
rm Boek_sensor_zonder_voorpagina.pdf
