#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

my_script_path=`realpath $0`
my_folder_path=`dirname $my_script_path`
build_folder=$my_folder_path/build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cd ..
cd Lessen
cd Voorwoord                ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_00.md; cd ..
cd 5_dc_motor_met_transistor; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_01.md; cd ..
cd 7_dc_motor_met_relais    ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_02.md; cd ..


cd $build_folder

cat README_00.md >> README.md; echo " " >> README.md
cat README_01.md >> README.md; echo " " >> README.md
cat README_02.md >> README.md; echo " " >> README.md

# Thinner margin
pandoc README.md -o boek.pdf --toc --toc-depth=1 --highlight-style=tango -V geometry:margin=0.5in

cp boek.pdf ../../Boek/Boek_actuatoren_hoog_zonder_voorpagina.pdf

cd ../../Boek

pdfunite VoorpaginaActuatorenHoog.pdf Boek_actuatoren_hoog_zonder_voorpagina.pdf Boek_actuatoren_hoog.pdf

# Make booklet
bookletimposer -a Boek_actuatoren_hoog.pdf -o Boekje_actuatoren_hoog.pdf

# Cleanup
rm Boek_actuatoren_hoog_zonder_voorpagina.pdf
